### ISSUE TITLE
Dataset Request

### ISSUE THREAD

**Issue by vateye** [XiaoMutt/xliniq#1]
Hello, I am not sure how can I download the dataset on the website. Would you mind telling me the details and steps? Thanks.

**Comment by XiaoMutt** [comment]
Please the steps here: https://www.clinicaltrials.gov/ct2/resources/download
To download the zip file containing all public data, enter the following URL into your browser:
https://clinicaltrials.gov/AllPublicXML.zip

**Comment by vateye** [comment]
`    mesh_trie = build_mesh_trie('../data/d2020.bin')
    ctdmc = build_clinical_trial_mesh_counts(mesh_trie, '../data/Sample.zip')
    with open('../output/Sample.ctdmc', 'wb') as f:
        pickle.dump(ctdmc, f)
`

How about these two files? (d2020.bin, Sample.zip) Where can I find these two files?
