### ISSUE TITLE
Some missing files

### ISSUE THREAD

**Issue by vateye** [XiaoMutt/xliniq#2]
`    mesh_trie = build_mesh_trie('../data/d2020.bin')
    ctdmc = build_clinical_trial_mesh_counts(mesh_trie, '../data/Sample.zip')
    with open('../output/Sample.ctdmc', 'wb') as f:
        pickle.dump(ctdmc, f)
`

How about these two files? (d2020.bin, Sample.zip) Where can I find these two files?

_Originally posted by @vateye in https://github.com/XiaoMutt/xliniq/issues/1#issuecomment-729338479_

**Comment by XiaoMutt** [comment]
the d2020.bin is the MeSH file which can be downloaded here: [https://www.nlm.nih.gov/databases/download/mesh.html](url)
the Sample.zip is the clinical trial records you downloaded from the clinical trial's official website
